networks:
  node-network:
    driver: bridge

services:
  
  app:
    build:
      context: ./node
    container_name: app
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      db:
        condition: service_healthy
    networks:
      - node-network
    ports:
      - "3000"

  db:
    build: 
      context: ./mysql
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/db:/var/lib/mysql
    networks:
      - node-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      app:
        condition: service_started
    volumes:
      - ./nginx:/etc/nginx/conf.db